package StaffPersonGUI;


import Frames.Store_Frame;
import vaccinationsystem.BarChart;
import vaccinationsystem.Store;
import vaccinationsystem.Vaccine;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import org.jfree.ui.RefineryUtilities;

public class StoreKeeperDashboard extends javax.swing.JFrame {

    /**
     * Creates new form StoreKeeperDashboard2
     */
    public StoreKeeperDashboard() {
        setLocation(250, 10);
        setTitle("Store Keeper Dashboard");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1_storeKeeper = new javax.swing.JMenuBar();
        jMenu1_back = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();
        jMenu1_store = new javax.swing.JMenu();
        jMenuItem1_store = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        generateReport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Desktop.setBackground(new java.awt.Color(51, 0, 51));

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );

        jMenu1_back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenu1_back.setText("File");

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1_back.add(exit);

        jMenuBar1_storeKeeper.add(jMenu1_back);

        jMenu1_store.setText("Store");
        jMenu1_store.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1_storeActionPerformed(evt);
            }
        });

        jMenuItem1_store.setText("Open Store");
        jMenuItem1_store.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_storeActionPerformed(evt);
            }
        });
        jMenu1_store.add(jMenuItem1_store);

        jMenuBar1_storeKeeper.add(jMenu1_store);

        jMenu1.setText("Report");

        generateReport.setText("Generate Report");
        generateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportActionPerformed(evt);
            }
        });
        jMenu1.add(generateReport);

        jMenuBar1_storeKeeper.add(jMenu1);

        setJMenuBar(jMenuBar1_storeKeeper);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Desktop))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Desktop))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1_storeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1_storeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1_storeActionPerformed

    private void jMenuItem1_storeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_storeActionPerformed
        // TODO add your handling code here:
        Store_Frame s = new Store_Frame();
        Desktop.add(s);
        s.setVisible(true);
    }//GEN-LAST:event_jMenuItem1_storeActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        int c = JOptionPane.showConfirmDialog(null, "Are you Sure, System will Exit");
        if (c == JOptionPane.OK_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed
    
    
    
    private void generateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReportActionPerformed
        // TODO add your handling code here:
        Store x = new Store();
        ArrayList<Store> stores = x.listStore();
        
        Vaccine v =new Vaccine();
      
        double[] values = new double[stores.size()];
        String[] names = new String[stores.size()];
        for (int i = 0; i < stores.size(); i++) {
            values[i] = stores.get(i).getsetstoreCapacity();
            //names[i] = stores.get(i).get_vacTradeName();
        }
        /*        for (int i = 0; i < 25; i++) {

            names[i] = "Item " + i;
            if (i % 2 == 0) {
                values[i] = i * 5 + 1;
            } else {
                values[i] = i * 3 + 2;
            }
        }
         */
        BarChart chart = new BarChart(" Store Report ", names, values);

        chart.pack();
        RefineryUtilities.centerFrameOnScreen(chart);
        chart.setVisible(true);
        
    }//GEN-LAST:event_generateReportActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StoreKeeperDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StoreKeeperDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StoreKeeperDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StoreKeeperDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StoreKeeperDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenuItem generateReport;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu1_back;
    private javax.swing.JMenu jMenu1_store;
    private javax.swing.JMenuBar jMenuBar1_storeKeeper;
    private javax.swing.JMenuItem jMenuItem1_store;
    // End of variables declaration//GEN-END:variables
}