package StaffPersonGUI;

import Store.Add_vaccine;
import Store.Edit_Vaccine;
import Store.List_Vaccine;
import java.util.ArrayList;
import vaccinationsystem.Store;
import vaccinationsystem.Vaccine;

public class StoreKeeperDashboard extends javax.swing.JFrame {

    /**
     * Creates new form StoreKeeperDashboard
     */
    public StoreKeeperDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jButton_ListVaccine = new javax.swing.JButton();
        jButtonAddVaccine = new javax.swing.JButton();
        jButton_GenerateReport = new javax.swing.JButton();
        jButton_EditVaccine = new javax.swing.JButton();
        jButton_deleteVaccine = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1_back = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        jButton_ListVaccine.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jButton_ListVaccine.setText("List Vaccine");
        jButton_ListVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ListVaccineActionPerformed(evt);
            }
        });

        jButtonAddVaccine.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jButtonAddVaccine.setText("Add Vaccine");
        jButtonAddVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddVaccineActionPerformed(evt);
            }
        });

        jButton_GenerateReport.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jButton_GenerateReport.setText("Generate Report");
        jButton_GenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GenerateReportActionPerformed(evt);
            }
        });

        jButton_EditVaccine.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jButton_EditVaccine.setText("Edit Vaccine");
        jButton_EditVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditVaccineActionPerformed(evt);
            }
        });

        jButton_deleteVaccine.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jButton_deleteVaccine.setText("Delete Vaccine");
        jButton_deleteVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteVaccineActionPerformed(evt);
            }
        });

        jMenu1_back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenu1_back.setText("Back");
        jMenuBar1.add(jMenu1_back);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_GenerateReport))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButtonAddVaccine))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jButton_EditVaccine)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(225, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_deleteVaccine)
                        .addGap(173, 173, 173))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_ListVaccine)
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButtonAddVaccine)
                .addGap(36, 36, 36)
                .addComponent(jButton_EditVaccine)
                .addGap(37, 37, 37)
                .addComponent(jButton_deleteVaccine)
                .addGap(37, 37, 37)
                .addComponent(jButton_ListVaccine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButton_GenerateReport)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Search");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_GenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GenerateReportActionPerformed
        // TODO add your handling code here:
        Store x = new Store();
        ArrayList<Store> s = x.listStore();
        double[] values = new double[s.size()];
        String[] names = new String[s.size()];
        for (int i = 0; i < s.size(); i++) {
            values[i] = s.get(i).getstoreId();
            values[i] = s.get(i).getstoreFreeSpace();
            values[i] = s.get(i).getsetstoreCapacity();
            
            Vaccine vac = new Vaccine();
            
            names[i] = vac.get(i).get_vacTradeName();
        }
        /*        for (int i = 0; i < 25; i++) {

            names[i] = "Item " + i;
            if (i % 2 == 0) {
                values[i] = i * 5 + 1;
            } else {
                values[i] = i * 3 + 2;
            }
        }
         */
        BarChart chart = new BarChart(" Store Report ", names, values);

        chart.pack();
        RefineryUtilities.centerFrameOnScreen(chart);
        chart.setVisible(true);
        
    }//GEN-LAST:event_jButton_GenerateReportActionPerformed

    private void jButtonAddVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddVaccineActionPerformed
        // TODO add your handling code here:
        Add_vaccine obj=new Add_vaccine();
        obj.setVisible(true);
        
    }//GEN-LAST:event_jButtonAddVaccineActionPerformed

    private void jButton_EditVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditVaccineActionPerformed
        // TODO add your handling code here:
       
        Edit_Vaccine obj2=new Edit_Vaccine();
        obj2.setVisible(true);
    }//GEN-LAST:event_jButton_EditVaccineActionPerformed

    private void jButton_ListVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ListVaccineActionPerformed
        // TODO add your handling code here:
        List_Vaccine obj3=new List_Vaccine();
        obj3.setVisible(true);
    }//GEN-LAST:event_jButton_ListVaccineActionPerformed

    private void jButton_deleteVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteVaccineActionPerformed
        // TODO add your handling code here:
        Edit_Vaccine obj2=new Edit_Vaccine();
        obj2.setVisible(true);
    }//GEN-LAST:event_jButton_deleteVaccineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StoreKeeperDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StoreKeeperDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StoreKeeperDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StoreKeeperDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StoreKeeperDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddVaccine;
    private javax.swing.JButton jButton_EditVaccine;
    private javax.swing.JButton jButton_GenerateReport;
    private javax.swing.JButton jButton_ListVaccine;
    private javax.swing.JButton jButton_deleteVaccine;
    private javax.swing.JMenu jMenu1_back;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
