package Frames.Panels;

import javax.swing.JOptionPane;
import vaccinationsystem.Store;
import vaccinationsystem.Vaccine;

/**
 *
 * @author Nagham
 */
public class StoreKeeper_EditVaccinePanel extends javax.swing.JPanel {

    /**
     * Creates new form StoreKeeper_EditVaccinePanel
     */
    public StoreKeeper_EditVaccinePanel() {
        initComponents();
        IDtxt.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Nametxt = new javax.swing.JTextField();
        IDtxt = new javax.swing.JTextField();
        abbrevationtxt = new javax.swing.JTextField();
        expirationtxt = new javax.swing.JTextField();
        typetxt = new javax.swing.JTextField();
        commenttxt = new javax.swing.JTextField();
        pricetxt = new javax.swing.JTextField();
        jButton1_update = new javax.swing.JButton();
        jButton2_delete = new javax.swing.JButton();
        searchtxt = new javax.swing.JTextField();
        jButton3_search = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Vaccine ID:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Vac Trade Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Vac Expiration Year:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Vac abbreviation:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Vac Type:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Vac Price:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Vac Comment:");

        Nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NametxtActionPerformed(evt);
            }
        });

        abbrevationtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abbrevationtxtActionPerformed(evt);
            }
        });

        jButton1_update.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton1_update.setText("Update");
        jButton1_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_updateActionPerformed(evt);
            }
        });

        jButton2_delete.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton2_delete.setText("Delete");
        jButton2_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_deleteActionPerformed(evt);
            }
        });

        jButton3_search.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton3_search.setText("Search");
        jButton3_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pricetxt)
                            .addComponent(commenttxt)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1_update, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(typetxt)
                                .addComponent(abbrevationtxt)
                                .addComponent(expirationtxt)
                                .addComponent(Nametxt)
                                .addComponent(IDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3_search)
                        .addGap(27, 27, 27)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3_search))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(IDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(expirationtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(typetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(pricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(commenttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(abbrevationtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_update)
                    .addComponent(jButton2_delete))
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NametxtActionPerformed

    private void abbrevationtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abbrevationtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abbrevationtxtActionPerformed

    private void jButton1_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_updateActionPerformed
        // TODO add your handling code here:
        if (!IDtxt.getText().equals("") && !typetxt.getText().equals("") && !Nametxt.getText().equals("") && !abbrevationtxt.getText().equals("") && !expirationtxt.getText().equals("") && !searchtxt.getText().equals("") && !pricetxt.getText().equals("") && !commenttxt.getText().equals("")) {

            Vaccine x = new Vaccine();
            x.set_vacId(Integer.parseInt(IDtxt.getText()));
            x.set_vacTradeName(Nametxt.getText());
            x.set_vacType(typetxt.getText());
            x.set_vacAbbreviation(abbrevationtxt.getText());
            x.set_comments(commenttxt.getText());
            x.set_vacExpirationYear(Integer.parseInt(expirationtxt.getText()));
            x.set_price(Integer.parseInt(pricetxt.getText()));

            if (x.updateVac()) {
                JOptionPane.showMessageDialog(null, "Updated Successfully ... !");
                resetPanelData();
            } else {

                JOptionPane.showMessageDialog(null, "Failed to Update ... !");

            }
        } else {

            JOptionPane.showMessageDialog(null, "Missing required Fields ... !  Please, complete them before submit .... !");

        }

    }//GEN-LAST:event_jButton1_updateActionPerformed

    private void jButton2_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_deleteActionPerformed
        // TODO add your handling code here:
        if (!searchtxt.getText().equals("")) {
            Vaccine x = new Vaccine();
            if (x.deleteVac(Integer.parseInt(searchtxt.getText()))) {
                JOptionPane.showMessageDialog(null, "Deleted Successfully ... !");
                resetPanelData();
            } else {
                JOptionPane.showMessageDialog(null, "Failed to Delete ... !");
            }
        } else {
            
            JOptionPane.showMessageDialog(null, "Missing required Fields ... !  Please, Search By ID before submit ... !");

        }
    }//GEN-LAST:event_jButton2_deleteActionPerformed

    private void jButton3_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_searchActionPerformed
      // TODO add your handling code here:
        if (!searchtxt.getText().equals("")) {
            Store x = new Store();
            Vaccine vac=new Vaccine();
            Store returned = x.searchVacById(Integer.parseInt(searchtxt.getText()));
            if (returned.vac.get_vacId()> 0) {
                setPanelData(returned);
            } else {
                JOptionPane.showMessageDialog(null, "Not Found ... !");
            }
        } else {

            JOptionPane.showMessageDialog(null, "Missing required Fields ... !  Please, Search By ID before submit ... !");

        }
    }//GEN-LAST:event_jButton3_searchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDtxt;
    private javax.swing.JTextField Nametxt;
    private javax.swing.JTextField abbrevationtxt;
    private javax.swing.JTextField commenttxt;
    private javax.swing.JTextField expirationtxt;
    private javax.swing.JButton jButton1_update;
    private javax.swing.JButton jButton2_delete;
    private javax.swing.JButton jButton3_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField pricetxt;
    private javax.swing.JTextField searchtxt;
    private javax.swing.JTextField typetxt;
    // End of variables declaration//GEN-END:variables

   protected void resetPanelData() {
        
       IDtxt.setText(null);
       Nametxt.setText(null);
       abbrevationtxt.setText(null);
       commenttxt.setText(null);
       expirationtxt.setText(null);
       pricetxt.setText(null);
       typetxt.setText(null);
       searchtxt.setText(null);
    }
   
   protected void setPanelData(Store x) {
        Vaccine v = new Vaccine();
        
        IDtxt.setText("" + v.get_vacId());
        Nametxt.setText("" + v.get_vacTradeName());
        abbrevationtxt.setText("" + v.get_vacAbbreviation());
        expirationtxt.setText("" + v.get_vacExpirationYear());
        typetxt.setText("" + v.get_vacType());
        commenttxt.setText("" + v.get_vacComment());
        pricetxt.setText("" + v.get_price());

    }
   
   
   
}
