/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Panels;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import vaccinationsystem.Vaccine;

/**
 *
 * @author Nagham
 */
public class StoreKeeper_ListVaccinePanel extends javax.swing.JPanel {

    /**
     * Creates new form StoreKeeper_ListVaccinePanel
     */
    public StoreKeeper_ListVaccinePanel() {
        initComponents();
        addRowsToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        VaccTable = new javax.swing.JTable();

        VaccTable.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        VaccTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vacc ID", "Vacc name", "Vacc type", "expiration date", "abbreviation", "price", "comment"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        VaccTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(VaccTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable VaccTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void addRowsToTable() {
        DefaultTableModel model = (DefaultTableModel) VaccTable.getModel();
        Object rowData[] = new Object[7];

        Vaccine vac = new Vaccine();
        ArrayList<Vaccine> vaccine = new ArrayList<Vaccine>();

        //vaccine = vac.listVac();
        vac.listVac();

        for (Vaccine x : vaccine) {
            rowData[0] = vac.get_vacId();
            rowData[1] = vac.get_vacTradeName();
            rowData[2] = vac.get_vacType();
            rowData[3] = vac.get_vacExpirationYear();
            rowData[4] = vac.get_vacAbbreviation();
            rowData[5] = vac.get_price();
            rowData[6] = vac.get_vacComment();
            model.addRow(rowData);
    }
}
        
        
}